language: java
jdk:
  - openjdk8

branches:
  only:
    - master
before_install:
  - chmod +x gradlew

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot01 *
  - mkdir -p deploy
  - mv springboot01.zip deploy/springboot01.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-jpa-build
    region: ap-northeast-2
    skip_cleanup: true
    acl : private
    local_dir: deploy
    wait-until-deployed : true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: springboot-jpa-build
    key: springboot01.zip

    bundle_type: zip
    application: springboot-jpa
    deployment_group: springboot-jpa-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알림
notifications:
  email:
    recipients:
      - cattaku0@gmail.com
